# Generated by Django 3.0.1 on 2020-01-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='faculity',
            fields=[
                ('factid', models.IntegerField(primary_key='True', serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('qualification', models.CharField(max_length=10)),
                ('mobile', models.IntegerField(blank=True, max_length=10, null=True)),
                ('email', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
                ('assbatch', models.CharField(max_length=10)),
            ],
        ),
    ]
