# Generated by Django 3.0.1 on 2020-01-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_faculity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculity',
            name='mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
