# Generated by Django 3.0.1 on 2020-01-06 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20200106_1654'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='faculity',
            new_name='facultysignup',
        ),
    ]
