# Generated by Django 3.0.1 on 2020-01-07 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20200106_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('stdid', models.IntegerField(primary_key=True, serialize=False)),
                ('admno', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('mobile', models.IntegerField(blank=True, max_length=10, null=True)),
                ('admdate', models.DateField(blank=True, null=True)),
                ('guardian', models.CharField(blank=True, max_length=10, null=True)),
                ('batch', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.CharField(blank=True, max_length=1, null=True)),
                ('password', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='facultysignup',
            name='factid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
