# Generated by Django 3.0.1 on 2020-01-07 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_auto_20200107_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
